id: IF7555510
legacy_id: P001735
ocr_import_info:
  bdrc_scan_id: W1KG23567
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T05:36:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:32:21.453199+00:00'
last_modified: 2022-08-31 21:32:33.676326
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG23567
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG23567
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བརྡ་ཡིག་ངག་སྒྲོན་རྫོང་ཁ་དང་ནེ་པ་ལི་ཤན་སྦྱར།
statistics:
  ocr_word_mean_confidence_index: 0.6682234488396632
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG23613:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG23613
      total_pages: 216
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG23613.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.6682234488396632
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
