id: IF7555510
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:37:59+00:00'
last_modified: '2022-06-07T14:14:42.756084+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23567
  title: བརྡ་ཡིག་ངག་སྒྲོན་རྫོང་ཁ་དང་ནེ་པ་ལི་ཤན་སྦྱར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5CC4:
      image_group_id: I1KG23613
      title: ''
      total_pages: 216
      order: 1
      base_file: 5CC4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
