id: P001735
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:17:29.922289
source_metadata:
  id: bdr:W1KG23567
  title: བརྡ་ཡིག་ངག་སྒྲོན་རྫོང་ཁ་དང་ནེ་པ་ལི་ཤན་སྦྱར།
  author: ''
  volumes:
    e3fc6e8e1f264a48ad189d95586bb5b1:
      image_group_id: I1KG23613
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
